name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  email_validator: ^3.0.0
  hive: ^2.2.3
  provider: ^6.1.2
  dot_navigation_bar: ^1.0.2
  cloud_firestore: ^5.0.2
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  intl: ^0.19.0
  youtube_player_flutter: ^8.1.2
  auto_size_text: ^3.0.0
  card_loading: ^0.3.2
  flutter_carousel_media_slider: ^0.0.2
  custom_video_player: ^1.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

