// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHJisf2FfwYvPWynHJXR6iRYD8rSMPrI',
    appId: '1:337002971912:android:39c198a77d7d84222fa2bd',
    messagingSenderId: '337002971912',
    projectId: 'myappauth-f5d33',
    databaseURL: 'https://myappauth-f5d33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myappauth-f5d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAfKUKyx2e8DGf3EDRK9OYn0ndZCgdI8',
    appId: '1:337002971912:ios:32edb76774a16e782fa2bd',
    messagingSenderId: '337002971912',
    projectId: 'myappauth-f5d33',
    databaseURL: 'https://myappauth-f5d33-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myappauth-f5d33.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
